### PR TITLE
Impl drop for arenas

### PR DESCRIPTION
**Pull request by kpp**
Closes: https://github.com/llogiq/compact_arena/issues/9

### CODE REVIEW

**Comment by llogiq** [comment]
Should we also implement drop for SmallArena?

**Comment by kpp** [comment]
There was no drop fn for SmallArena ;)

**Comment by Fedcomp** [comment]
@llogiq @kpp I think it's reasonable to post this link
https://github.com/rust-unofficial/patterns/blob/master/anti_patterns/deny-warnings.md
You may ignore it, i just want you to be aware of it.

**Comment by llogiq** [comment]
Thanks, I may push it to CI args in a future version.

**Pull request merged**
